-- 0044: log unificado de emails salientes hacia leads — para poder ver en la
-- ficha del contacto TODO lo que se le mandó (manual desde el dashboard, IA
-- de un workflow, nurture, confirmación de booking, calculadora), sin importar
-- quién lo mandó (Sofia/Sebastian/sistema) ni desde qué función salió.
-- No cubre emails ENTRANTES (respuestas del cliente por Gmail) — eso requiere
-- sync de bandeja de entrada, que quedó afuera de este alcance.

create table if not exists public.email_log (
  id bigint generated by default as identity primary key,
  lead_id text,
  to_addr text,
  subject text,
  body text,
  sender_label text,     -- 'Sofia' | 'Sebastian' | 'VIVEN (team)' | etc.
  source text,           -- 'outreach' | 'automations-run' | 'nurture' | 'booking-create' | 'calc-email'
  created_at timestamptz not null default now()
);
create index if not exists email_log_lead_idx on public.email_log (lead_id, created_at desc);

alter table public.email_log enable row level security;

do $$ begin
  create policy "email_log_auth_all" on public.email_log for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
