-- Insert 2 nuevos borradores de Employer Branding directo en la tabla
-- blogs (bypass del content-engine AI, contenido escrito a mano por Claude),
-- listos para que Sebastián los revise y publique desde el dashboard el
-- viernes y la semana que viene respectivamente. status='draft' — nadie los
-- ve hasta que se publiquen manualmente.

with g1 as (select gen_random_uuid() as id)
insert into public.blogs (group_id, lang, slug, topic, title, description, eyebrow, lead, body_html, category, hero_image, status)
select id, 'en', 'how-much-does-an-employer-branding-video-cost', 'How much does an employer branding video cost', 'How Much Does an Employer Branding Video Cost?', 'Employer branding video pricing depends on scope, not the label. What actually drives the price, why the cheapest quote often costs more, and how to get a real number.', 'Employer Branding', 'It''s the first question every HR or marketing lead asks — and the honest answer is that "employer branding video" isn''t a price, it''s a scope. Here''s what actually moves the number.', '<h2>What actually drives the price</h2>
<p>Two projects both called "employer branding video" can land at very different numbers, because what moves the price isn''t the label — it''s the scope. Crew size, how many people you''re interviewing or following, how many locations and days on site, and how many language versions you need at the end all matter more than the topic itself.</p>
<h2>The wrong first question</h2>
<p>"How much for an employer branding video?" is the wrong question to start with. The honest starting point is: what job does this video need to do? A single hero piece for your careers page is a different production than a full recruiting campaign meant to run across LinkedIn, job ads and onboarding. Scope follows the job — the price follows the scope.</p>
<h2>Why the cheapest quote is usually the most expensive one</h2>
<p>A low bid that skips pre-production, brings a crew unfamiliar with your industry, or under-budgets editing almost always costs more in the end — in rework, in delays, or in a film that never actually moves the numbers it was meant to move. The real comparison isn''t quote against quote. It''s quote against what the finished film is worth to you.</p>
<h2>Get a real number</h2>
<p>Rather than guess from a blog post, answer five quick questions in our <a href="/en/video-cost-calculator/">free cost calculator</a> and get an honest CHF range in under a minute — based on real Viven projects, not industry averages.</p>', 'employer', '/projects/ubs-more-than-code-employer-branding/05-S_Tech_Employer_Branding_Campaign_1.jpeg', 'draft' from g1
union all
select id, 'de', 'was-kostet-ein-employer-branding-video', 'Was kostet ein Employer-Branding-Video', 'Was kostet ein Employer-Branding-Video?', 'Der Preis eines Employer-Branding-Videos hängt vom Umfang ab, nicht vom Begriff. Was den Preis wirklich treibt, warum das günstigste Angebot oft am teuersten ist, und wie Sie eine echte Zahl bekommen.', 'Employer Branding', 'Es ist die erste Frage, die jede HR- oder Marketingleitung stellt — und die ehrliche Antwort ist: «Employer-Branding-Video» ist kein Preis, sondern ein Umfang. Das bewegt die Zahl wirklich.', '<h2>Was den Preis wirklich treibt</h2>
<p>Zwei Projekte, beide «Employer-Branding-Video» genannt, können bei sehr unterschiedlichen Summen landen — denn was den Preis bewegt, ist nicht der Begriff, sondern der Umfang. Teamgrösse, wie viele Personen Sie interviewen oder begleiten, wie viele Drehorte und Drehtage, und wie viele Sprachversionen Sie am Ende brauchen, zählen mehr als das Thema selbst.</p>
<h2>Die falsche erste Frage</h2>
<p>«Was kostet ein Employer-Branding-Video?» ist die falsche Frage zum Einstieg. Der ehrliche Ausgangspunkt lautet: Welche Aufgabe muss dieses Video erfüllen? Ein einzelnes Hero-Video für Ihre Karriereseite ist eine andere Produktion als eine vollständige Recruiting-Kampagne für LinkedIn, Stelleninserate und Onboarding. Der Umfang folgt der Aufgabe — der Preis folgt dem Umfang.</p>
<h2>Warum das günstigste Angebot meist das teuerste ist</h2>
<p>Ein niedriges Angebot, das Vorproduktion überspringt, ein branchenfremdes Team mitbringt oder beim Schnitt zu knapp kalkuliert, kostet am Ende fast immer mehr — durch Nacharbeit, Verzögerungen oder einen Film, der die Zahlen nie bewegt, für die er gedacht war. Der eigentliche Vergleich ist nicht Angebot gegen Angebot. Es ist Angebot gegen das, was der fertige Film Ihnen wert ist.</p>
<h2>Eine echte Zahl bekommen</h2>
<p>Statt aus einem Blogartikel zu raten, beantworten Sie fünf kurze Fragen in unserem <a href="/de/videoproduktion-kosten-rechner/">kostenlosen Kostenrechner</a> und erhalten in unter einer Minute eine ehrliche CHF-Spanne — basierend auf echten Viven-Projekten, nicht auf Branchendurchschnitten.</p>', 'employer', '/projects/ubs-more-than-code-employer-branding/05-S_Tech_Employer_Branding_Campaign_1.jpeg', 'draft' from g1
union all
select id, 'es', 'cuanto-cuesta-un-video-de-employer-branding', 'Cuánto cuesta un video de employer branding', '¿Cuánto cuesta un video de employer branding?', 'El precio de un video de employer branding depende del alcance, no de la etiqueta. Qué mueve realmente el precio, por qué el presupuesto más barato suele ser el más caro, y cómo conseguir un número real.', 'Employer Branding', 'Es la primera pregunta que hace cualquier responsable de RRHH o marketing — y la respuesta honesta es que "video de employer branding" no es un precio, es un alcance. Esto es lo que realmente mueve el número.', '<h2>Qué mueve realmente el precio</h2>
<p>Dos proyectos, ambos llamados "video de employer branding", pueden terminar en números muy distintos, porque lo que mueve el precio no es la etiqueta: es el alcance. El tamaño del equipo, cuánta gente entrevistás o seguís, cuántas locaciones y días de rodaje, y cuántas versiones de idioma necesitás al final pesan más que el tema en sí.</p>
<h2>La pregunta equivocada para empezar</h2>
<p>"¿Cuánto cuesta un video de employer branding?" es la pregunta equivocada para arrancar. El punto de partida honesto es: ¿qué trabajo tiene que hacer este video? Una sola pieza para tu página de carreras es una producción distinta de una campaña de reclutamiento completa para LinkedIn, avisos de empleo y onboarding. El alcance sigue al trabajo — el precio sigue al alcance.</p>
<h2>Por qué el presupuesto más barato suele ser el más caro</h2>
<p>Un presupuesto bajo que se salta la preproducción, trae un equipo que no conoce tu industria, o subestima la edición, casi siempre termina costando más — en retrabajo, en demoras, o en un film que nunca mueve los números para los que se pensó. La comparación real no es presupuesto contra presupuesto. Es presupuesto contra lo que vale el film terminado para vos.</p>
<h2>Conseguí un número real</h2>
<p>En vez de adivinar desde un blog, respondé cinco preguntas rápidas en nuestra <a href="/es/calculadora-costos-video/">calculadora gratis</a> y conseguí un rango honesto en CHF en menos de un minuto — basado en proyectos reales de Viven, no en promedios de la industria.</p>', 'employer', '/projects/ubs-more-than-code-employer-branding/05-S_Tech_Employer_Branding_Campaign_1.jpeg', 'draft' from g1;

with g2 as (select gen_random_uuid() as id)
insert into public.blogs (group_id, lang, slug, topic, title, description, eyebrow, lead, body_html, category, hero_image, status)
select id, 'en', 'what-we-learned-producing-employer-branding-films-for-ubs-siemens-and-kpmg', 'Lessons from producing employer branding films for UBS, Siemens and KPMG', 'What We Learned Producing Employer Branding Films for UBS, Siemens and KPMG', 'Three very different companies, three employer branding films, one recurring lesson: what actually makes enterprise employer branding work.', 'Employer Branding', 'UBS, Siemens and KPMG don''t compete for the same talent, and their employer branding films don''t look alike either. But producing all three taught us the same thing about what large-enterprise employer branding actually requires.', '<h2>Scale doesn''t excuse genericness</h2>
<p>The instinct with a large, well-known employer is to lean on the logo and let it do the work. It never does. UBS, Siemens and KPMG are recognizable brands, but the films that actually move candidates are the ones that show specific people doing specific work — not an abstract idea of "a great place to work."</p>
<h2>Internal buy-in takes longer than the shoot</h2>
<p>With enterprise clients, the production itself is rarely the bottleneck — alignment is. Legal, HR, communications and the business unit each have a stake in how the company is represented, and that alignment has to happen before a camera rolls, not during the edit. Building that time into the schedule up front is what keeps a project like this from stalling.</p>
<h2>One film, more than one job</h2>
<p>None of these three films were built for a single channel. The same footage ended up on careers pages, in LinkedIn campaigns, in onboarding decks and shared internally by employees themselves. Planning for that from the brief — not just the recruiting use case — is what made the same production keep paying off months later.</p>
<h2>The craft has to hold up at enterprise scrutiny</h2>
<p>A film representing a bank, an industrial engineering company and a global consultancy gets reviewed by more people, more carefully, than most marketing content ever will. That level of scrutiny rewards real filmmaking discipline — considered shots, a real story — over anything that reads as generic corporate video.</p>
<p>See the <a href="/en/projects/">full case studies</a>, or <a href="/en/contact/">tell us about your own employer branding project</a>.</p>', 'employer', '/projects/de/siemens-mobility-employer-branding-kampagne/07-Siemens_Mobility_Brand_Video_4.jpeg', 'draft' from g2
union all
select id, 'de', 'was-wir-bei-employer-branding-filmen-fuer-ubs-siemens-und-kpmg-gelernt-haben', 'Lektionen aus Employer-Branding-Filmen für UBS, Siemens und KPMG', 'Was wir bei Employer-Branding-Filmen für UBS, Siemens und KPMG gelernt haben', 'Drei sehr unterschiedliche Unternehmen, drei Employer-Branding-Filme, eine wiederkehrende Lektion: was Employer Branding auf Konzernebene wirklich braucht.', 'Employer Branding', 'UBS, Siemens und KPMG konkurrieren nicht um dieselben Talente, und ihre Employer-Branding-Filme sehen sich auch nicht ähnlich. Aber die Produktion aller drei hat uns dasselbe über Employer Branding auf Konzernebene gelehrt.', '<h2>Grösse entschuldigt keine Beliebigkeit</h2>
<p>Der Instinkt bei einem grossen, bekannten Arbeitgeber ist, sich auf das Logo zu verlassen und es die Arbeit machen zu lassen. Das funktioniert nie. UBS, Siemens und KPMG sind bekannte Marken, aber die Filme, die Kandidat:innen wirklich bewegen, zeigen konkrete Menschen bei konkreter Arbeit — nicht eine abstrakte Idee von «ein toller Arbeitsplatz».</p>
<h2>Interne Abstimmung dauert länger als der Dreh</h2>
<p>Bei Grosskund:innen ist selten die Produktion selbst der Engpass — es ist die Abstimmung. Rechtsabteilung, HR, Kommunikation und der jeweilige Geschäftsbereich haben alle ein Interesse daran, wie das Unternehmen dargestellt wird, und diese Abstimmung muss passieren, bevor die Kamera läuft, nicht während des Schnitts. Diese Zeit von Anfang an im Zeitplan einzuplanen, verhindert, dass ein Projekt wie dieses ins Stocken gerät.</p>
<h2>Ein Film, mehr als eine Aufgabe</h2>
<p>Keiner dieser drei Filme wurde für einen einzigen Kanal gebaut. Dasselbe Material landete am Ende auf Karriereseiten, in LinkedIn-Kampagnen, in Onboarding-Unterlagen und wurde von Mitarbeitenden selbst intern geteilt. Das schon im Briefing mitzudenken — nicht nur den Recruiting-Anwendungsfall — ist, was dieselbe Produktion Monate später noch weiter auszahlen liess.</p>
<h2>Das Handwerk muss der Konzern-Prüfung standhalten</h2>
<p>Ein Film, der eine Bank, ein Industrieunternehmen und eine globale Beratung repräsentiert, wird von mehr Menschen sorgfältiger geprüft als die meisten Marketinginhalte je werden. Dieses Mass an Prüfung belohnt echtes filmisches Handwerk — durchdachte Einstellungen, eine echte Geschichte — mehr als alles, was wie generisches Unternehmensvideo wirkt.</p>
<p>Sehen Sie die <a href="/de/projects/">vollständigen Case Studies</a>, oder <a href="/de/contact/">erzählen Sie uns von Ihrem eigenen Employer-Branding-Projekt</a>.</p>', 'employer', '/projects/de/siemens-mobility-employer-branding-kampagne/07-Siemens_Mobility_Brand_Video_4.jpeg', 'draft' from g2
union all
select id, 'es', 'que-aprendimos-produciendo-films-de-employer-branding-para-ubs-siemens-y-kpmg', 'Lecciones de producir films de employer branding para UBS, Siemens y KPMG', 'Qué aprendimos produciendo films de employer branding para UBS, Siemens y KPMG', 'Tres empresas muy distintas, tres films de employer branding, una lección que se repite: qué necesita realmente el employer branding a nivel corporativo.', 'Employer Branding', 'UBS, Siemens y KPMG no compiten por el mismo talento, y sus films de employer branding tampoco se parecen entre sí. Pero producir los tres nos enseñó lo mismo sobre qué necesita realmente el employer branding a gran escala.', '<h2>La escala no disculpa lo genérico</h2>
<p>El instinto con un empleador grande y conocido es apoyarse en el logo y dejar que haga el trabajo. Nunca funciona. UBS, Siemens y KPMG son marcas reconocibles, pero los films que realmente mueven a los candidatos son los que muestran gente concreta haciendo trabajo concreto — no una idea abstracta de "un gran lugar para trabajar".</p>
<h2>El acuerdo interno tarda más que el rodaje</h2>
<p>Con clientes corporativos, la producción en sí rara vez es el cuello de botella: lo es el alineamiento. Legal, RRHH, comunicación y el área de negocio tienen cada uno interés en cómo se representa a la empresa, y ese alineamiento tiene que pasar antes de que ruede la cámara, no durante la edición. Meter ese tiempo en el cronograma desde el principio es lo que evita que un proyecto así se trabe.</p>
<h2>Un film, más de un trabajo</h2>
<p>Ninguno de estos tres films se pensó para un solo canal. El mismo material terminó en páginas de carreras, en campañas de LinkedIn, en materiales de onboarding y compartido puertas adentro por los propios empleados. Pensar eso desde el brief —no solo el caso de uso de reclutamiento— es lo que hizo que la misma producción siguiera rindiendo meses después.</p>
<h2>El oficio tiene que aguantar el escrutinio corporativo</h2>
<p>Un film que representa a un banco, una empresa industrial y una consultora global lo revisa más gente, con más cuidado, que casi cualquier otro contenido de marketing. Ese nivel de escrutinio premia la disciplina real de cine —planos pensados, una historia real— por encima de cualquier cosa que se sienta como video corporativo genérico.</p>
<p>Mirá los <a href="/es/projects/">casos completos</a>, o <a href="/es/contact/">contanos sobre tu propio proyecto de employer branding</a>.</p>', 'employer', '/projects/de/siemens-mobility-employer-branding-kampagne/07-Siemens_Mobility_Brand_Video_4.jpeg', 'draft' from g2;
